#!/bin/bash

mkdir -p reports

PREFIX="run sitka.nf -resume -with-timeline reports/timeline.html -with-report reports/report.html -with-trace reports/trace.txt -with-dag reports/dag.dot "

if [ -n "$DISPLAY" ]; then 
  ./nextflow $PREFIX "$@" | nf-monitor --open true
else 
  command -v xvfb-run >/dev/null 2>&1 || { echo >&2 "If $DISPLAY not set, need to install 'sudo apt-get install xvfb libxrender1 libxtst6 libxi6 '"; exit 1; }
  xvfb-run ./nextflow $PREFIX "$@" | nf-monitor --open false
fi

